# --- General Settings ---
backend = "xrender";
vsync = false;
use-damage = true;
#glx-no-stencil = true;
#glx-copy-from-front = false;

# --- Animations (pijulius fork) ---
animations = true;
animation-stiffness = 300.0;
animation-damping = 25.0;
animation-clamping = true;
animation-mass = 1;

# Animation styles ("zoom", "fly-in", "slide-up", "slide-left", etc.)
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-transient-window = "slide-up";

# --- Fading ---
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 5;

# --- Corners & Shadows (Optional) ---
corner-radius = 1;
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.7;

# --- Exclude Rules ---
# Stops animations/shadows on dwm bar or slock to prevent visual bugs
# Wyłączenie cieni pod paskiem dwm
shadow-exclude = [
    "window_type = 'dock'",
    "class_g = 'dwm'",
    "_GTK_FRAME_EXTENTS@:c"
];

animation-exclude = [
  "class_g = 'dwm'"
];

wintypes:
{
    dock = { shadow = false; fade = false; }
    dmenu = { shadow = false; fade = false; }
};
